InternetAuction.Web/ViewModels/BetViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InternetAuction.Web.ViewModels
{
    public class BetViewModel
    {
        [Required]
        public int LotId { get; set; }

        [Required, Display(Name = "Sum($)")]
        public int Sum { get; set; }
    }
}

InternetAuction.Web/Controllers/BetController.cs
using InternetAuction.BLL.Interfaces;
using InternetAuction.BLL.Models;
using InternetAuction.Web.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace InternetAuction.Web.Controllers
{
    /// <summary>
    /// Represents bet controller class
    /// </summary>
    [Authorize]
    public class BetController : Controller
    {
        private readonly IBetService _betService;

        /// <summary>
        /// Initializes an instance of the bet controller with bet service
        /// </summary>
        /// <param name="betService"></param>
        public BetController(IBetService betService)
        {
            _betService = betService;
        }

        /// <summary>
        /// Adds a bet
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> PlaceBet(BetViewModel model)
        {
            if (ModelState.IsValid)
            {
                var betModel = new BetModel
                {
                    LotId = model.LotId,
                    UserId = User.Identity.GetUserId(),
                    Sum = model.Sum,
                    BetDate = DateTime.UtcNow
                };

                var result = await _betService.AddAsync(betModel);

                if (result.Succedeed)
                {
                    TempData["BetAccepted"] = "Your bet has been accepted";
                    return RedirectToAction("Details", "Lots", new { id = model.LotId });
                }

                foreach (var error in result.ValidationResults)
                {
                    ModelState.AddModelError(error.MemberNames.First(), error.ErrorMessage);
                }
            }

            return PartialView("PlaceBetPartial");
        }

        protected override void Dispose(bool disposing)
        {
            _betService.Dispose();
            base.Dispose(disposing);
        }
    }
}

InternetAuction.Web/Views/Bet/PlaceBetPartial.cshtml
@model InternetAuction.Web.ViewModels.BetViewModel

@using (Html.BeginForm("PlaceBet", "Bet", FormMethod.Post, new { id = "form" }))
{
    @Html.AntiForgeryToken()
    
    <h3 class="font-weight-light">Place a bet</h3>

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.LotId)

        <div class="form-group p-0">
            @Html.LabelFor(model => model.Sum, htmlAttributes: new { @class = "control-label col-lg-12" })
            <div class="col-lg-12 p-0">
                @Html.EditorFor(model => model.Sum, new { htmlAttributes = new { @class = "form-control", required = "" } })
                @Html.ValidationMessageFor(model => model.Sum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-12">
                <input type="submit" value="Place a bet" class="btn btn-dark col-12" />
            </div>
        </div>
    </div>
}